### ISSUE TITLE
Setting saved code to CodeMirror editor

### ISSUE THREAD

**Issue by hondihon** [hondihon/Moding#13]
Javascript...

**Comment by star3058** [comment]
result = result.stringByReplacingOccurrencesOfString("\\n", withString: "\\\n") // 코드 상 print문 내부의 new line character
result = result.stringByReplacingOccurrencesOfString("\n", withString: "\\n") // new line character
                    result = result.stringByReplacingOccurrencesOfString("'", withString: "\\'") // ' 처리
                    result = result.stringByReplacingOccurrencesOfString("\\t", withString: "\\\t") // tab character
